version: '2'
services:
  mirakurun:
    build:
        context: mirakurun
    container_name: mirakurun
    privileged: true
    ports:
      - "40772:40772"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /var/local/tv-system/mirakurun/conf:/usr/local/etc/mirakurun
     - /var/local/tv-system/mirakurun/db:/usr/local/var/db/mirakurun
    devices:
     - /dev/bus/usb/*:/dev/bus/usb/*

  chinachu:
    build:
        context: chinachu
        args:
         - REPOSITORY=git://github.com/Chinachu/Chinachu.git
         - BRANCH=gamma
    container_name: chinachu
    ports:
     - "10772:10772"
     - "20772:20772"
     - "5354:5354/udp"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /var/local/tv-system/chinachu/conf/config.json:/usr/local/chinachu/config.json
     - /var/local/tv-system/chinachu/conf/rules.json:/usr/local/chinachu/rules.json
     - /var/local/tv-system/chinachu/data:/usr/local/chinachu/data
     - /var/local/tv-system/rec:/usr/local/chinachu/recorded
    links:
     - mirakurun:container-mirakurun
